version: '2'

volumes:
  postgres_data: {}

services:
  postgresql:
    image: postgres:9.5.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=fridgesaver
      - POSTGRES_DB=fridgesaver
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8090

#Todo build all service for production mod and deploy using kubernetes